on: [push, pull_request]

name: build

jobs:
  build:
    name: Check package
    uses: r-quantities/workflows/.github/workflows/build.yml@main
    secrets: inherit

  upstream:
    name: Check upstream
    needs: build
    uses: r-quantities/workflows/.github/workflows/upstream.yml@main
    secrets: inherit
